### PR TITLE
feat: add revision range support

### PR DESCRIPTION
**Pull request by dinoboff**
Revision range allow topological query, e.g. to query all tags from the current branch.

### CODE REVIEW

**Comment by dinoboff** [comment]
@ikhemissi ready for review

**Comment by ikhemissi** [comment]
Thank you very much @dinoboff for the contribution.
I'm happy with the changes you are suggesting, but I will have to merge this PR after https://github.com/ikhemissi/tagged-versions/pull/13.
Would you please update your PR to include the latest changes (the ones included in https://github.com/ikhemissi/tagged-versions/pull/13) ?

Thanks again

**Comment by ikhemissi** [comment]
Released in version 1.3.0

**Comment by dinoboff** [comment]
Thanks

**Pull request merged**
